### ISSUE TITLE
IT吐槽网-黑壳网提供

### ISSUE THREAD

**Issue by ykz200** [ykz200/Black#5]
https://bbs.blackdir.com 

 IT吐槽网,黑壳网旗下专门提供IT吐槽网服务，为小众IT人士服务，吐露自己工作日常面试的烦心事。.

**Comment by ykz200** [comment]
你们觉得优衣库的衬衫怎么样，突然超喜欢穿衬衫

**Comment by liudandandear** [comment]
test

**Comment by wangzhi8910** [comment]
123123

**Comment by ZYTSingleNoble** [comment]
没什么吐槽的，就是觉得薪资低，自己干还担不起风险，丧的很

**Comment by zjz2009000** [comment]
成都璟和网络 科技公司 老板 柏凤才,股东陈亦文 ,古成虹～～有项目就找人 做 做完不给工资～～然后跑路～～～接着重新开公司～～重新找人～～这样的套路已经 7，8次了～～已申请劳动仲裁 ～然后相关部门 也管不了～～请大家记住这些人 不要上当受骗～～

**Comment by homesangsang** [comment]
别人家公司都放假了！！！！我们还要战斗到周五

**Comment by flakedZZ** [comment]
## 国内就没有办法治一治这种996还拿不到加班费的情况吗

**Comment by ykz200** [comment]
> @flakedZZ
> ## 国内就没有办法治一治这种996还拿不到加班费的情况吗

法律分析：

996工作制，主要是指早上9点上班，晚上9点下班，中午休息1-2小时，一周工作6天。该工作制普遍存在于创业公司及互联网公司，但不符合法律规定。

首先，《劳动法》规定每日工作时间不超过8小时、平均每周不超过44小时。用人单位因生产经营需要可以延长工作时间，但每日不得超过1小时；因特殊原因还需延长工作时间的，在保障劳动者身体健康的条件下延长工作时间每日不得超过3小时，但每月不得超过36小时。而996工作制每周工作时间60个小时，远远超过了法定标准。
其次，单位实行综合计算工时制或不定时工时制，虽不需要计算每天的工作时间，但必须经由劳动部门审批同意才能适用。996工作制不属于法定工时制度，将其作为对工作时间的约定约束员工违反法律规定。

第三，企业文化是企业在实践中逐步形成的为全体员工所认同、遵守、带有本企业特色的价值观念。而把996工作制作为一种企业文化让劳动者接受既不合法，也违背企业文化的核心理念。

**Comment by tikmiss** [comment]
test

**Comment by ganwenbo** [comment]
Hello world

**Comment by kokoyuo** [comment]
http://www.blackdir.com/jump/index 是你的吗？
查询好多中文都报错比如说《大圣》

**Comment by kokoyuo** [comment]
FreeMarker template error (DEBUG mode; use RETHROW in production!): The following has evaluated to null or missing: ==> recordsSize [in template "companyInfo/content.ftl" at line 29, column 18] ---- Tip: If the failing expression is known to be legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)?? ---- ---- FTL stack trace ("~" means nesting-related): - Failed at: #if recordsSize != 0 [in template "companyInfo/content.ftl" at line 29, column 13] ---- Java stack trace (for programmers): ---- freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...] at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:134) at freemarker.core.EvalUtil.compare(EvalUtil.java:196) at freemarker.core.EvalUtil.compare(EvalUtil.java:113) at freemarker.core.ComparisonExpression.evalToBoolean(ComparisonExpression.java:62) at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:48) at freemarker.core.Environment.visit(Environment.java:326) at freemarker.core.Environment.visit(Environment.java:332) at freemarker.core.Environment.process(Environment.java:305) at freemarker.template.Template.process(Template.java:378) at org.springframework.web.servlet.view.freemarker.FreeMarkerView.processTemplate(FreeMarkerView.java:367) at org.springframework.web.servlet.view.freemarker.FreeMarkerView.doRender(FreeMarkerView.java:284) at org.springframework.web.servlet.view.freemarker.FreeMarkerView.renderMergedTemplateModel(FreeMarkerView.java:234) at org.springframework.web.servlet.view.AbstractTemplateView.renderMergedOutputModel(AbstractTemplateView.java:167) at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:303) at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1286) at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1041) at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:984) at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650) at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:206) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637) at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548) at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190) at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595) at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188) at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253) at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168) at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473) at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564) at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166) at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) at org.eclipse.jetty.server.Server.handle(Server.java:564) at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317) at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279) at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110) at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124) at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:673) at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:591) at java.lang.Thread.run(Thread.java:748)

**Comment by ykz200** [comment]
> http://www.blackdir.com/jump/index 是你的吗？
> 查询好多中文都报错比如说《大圣》

近期会进行新版本的发布，会彻底解决这些问题

**Comment by nobaidu** [comment]
1
